apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-conf
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    receivers:
      filelog:
        include:
          - /tetragon/tetragon.log
        start_at: beginning
    exporters:
      coralogix:
        domain: '{{ .Values.domain }}'
        private_key: ${PRIVATE_KEY}
        application_name: '{{ .Values.application_name }}'
        subsystem_name: '{{ .Values.subsystem_name }}'
        timeout: 30s
    service:
      pipelines:
        logs:
          receivers:
            - filelog
          exporters:
            - coralogix
