ignore_older: 3h
filebeat.modules:
- module: google_workspace
  saml:
    enabled: true
    var.jwt_file: "/tmp/gws_creds/gws-creds.json"
    var.delegated_account: "<email address>"
  user_accounts:
    enabled: true
    var.jwt_file: "/tmp/gws_creds/gws-creds.json"
    var.delegated_account: "<email address>"
  login:
    enabled: true
    var.jwt_file: "/tmp/gws_creds/gws-creds.json"
    var.delegated_account: "<email address>"
  admin:
    enabled: true
    var.jwt_file: "/tmp/gws_creds/gws-creds.json"
    var.delegated_account: "<email address>"
  drive:
    enabled: true
    var.jwt_file: "/tmp/gws_creds/gws-creds.json"
    var.delegated_account: "<email address>"
  groups:
    enabled: true
    var.jwt_file: "/tmp/gws_creds/gws-creds.json"
    var.delegated_account: "<email address>"

fields_under_root: true

processors:
- drop_fields:
    fields:
    - event.original
    ignore_missing: true

logging:
  level: debug
  to_files: true
  files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 10
  permissions: 0644

output.logstash:
  hosts: ["localhost:2024"]
