receivers:
 tcplog:
    listen_address: "0.0.0.0:2024"
exporters:
  coralogix:
    domain: "<coralogix domain>"
    private_key: "< send data key>"
    application_name: "<app name>"
    subsystem_name: "<sub name>"
    timeout: 30s
service:
  pipelines:
    logs:
      receivers: [ tcplog ]
      exporters: [ coralogix ]
