eventsapibeat:
  insecure_skip_verify: false
  signin_attempts:
    enabled: true
    auth_token: ""
    sample_frequency: "10s"
    cursor_state_file: "signinattempts.eventsapibeatstate"
    starting_cursor: >
      { "limit": 1000, "start_time": "2020-01-01T00:00:00Z" }
  item_usages:
    enabled: true
    auth_token: ""
    sample_frequency: "10s"
    cursor_state_file: "itemusages.eventsapibeatstate"
    starting_cursor: >
      { "limit": 1000, "start_time": "2020-01-01T00:00:00Z" }
  audit_events:
    enabled: true
    auth_token: ""
    sample_frequency: "10s"
    cursor_state_file: "auditevents.eventsapibeatstate"
    starting_cursor: >
      { "limit": 1000, "start_time": "2020-01-01T00:00:00Z" }

output.logstash:
  hosts: ["localhost:3024"]
